# Generated by Django 3.2.9 on 2021-12-02 08:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='category',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='total_borrow_count',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='borrowed_by',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_by', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='board_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.boardgame'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='games.Genre'),
        ),
    ]
