# Generated by Django 3.2.9 on 2021-11-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20211125_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='total_borrow_count',
        ),
    ]
